modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/ruvaldak/translucencyfix/issues"
license = "MIT"

[[mods]]
modId = "translucencyfix"
version = "${version}"
displayName = "Translucency Fix"
logoFile="assets/translucencyfix/icon.png"
authors = "ruvaldak"
description = '''
enables translucency for HUD and GUIs in Minecraft
'''
#logoFile = ""

[[dependencies.translucencyfix]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.translucencyfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.0,)"
ordering = "NONE"
side = "BOTH"